import {
  heroCheckCircle,
  heroExclamationCircle,
  heroInformationCircle,
  heroQuestionMarkCircle,
  heroXCircle,
  heroShieldCheck,
  heroShieldExclamation,
  heroCheckBadge,
  heroHandRaised,
  heroHome,
  heroNoSymbol,
  heroUserCircle,
  heroLockClosed,
  heroLockOpen,
  heroBars3,
  heroCog6Tooth,
} from '@ng-icons/heroicons/outline';

export const includedIcons: Record<string, string> = {
  heroCheckCircle,
  heroExclamationCircle,
  heroInformationCircle,
  heroQuestionMarkCircle,
  heroXCircle,
  heroShieldCheck,
  heroShieldExclamation,
  heroCheckBadge,
  heroHandRaised,
  heroHome,
  heroNoSymbol,
  heroUserCircle,
  heroLockClosed,
  heroLockOpen,
  heroBars3,
  heroCog6Tooth,
};
